feat: CLI commands for secondary indexes
sourcenetwork/defradb pull request #1595
Opened 2023-06-27 08:39 UTC by islamaliev

## Relevant issue(s)

Resolves #1553 

## Description

Adds following CLI commands:
- `client index create` that creates a new index on an existing collection
- `client index drop` that drop a named indexes on a collection
- `client index list` that lists all existing indexes in db or indexes for a specific collection

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [ ] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Unit test, integration tests, manual tests

Specify the platform(s) on which this was tested:
- MacOS

2023-06-27 16:02 UTC, fredcarle requested changes
Good work Islam! I do have a few things that I'd like to see changed and discussed as you'll see bellow.

2023-06-27 19:49 UTC, islamaliev commented on api/http/handlerfuncs.go
> +	}
`client.IndexDescription` doesn't have `json` tags

2023-06-27 20:42 UTC, fredcarle commented on api/http/handlerfuncs.go
> +	}
You can add them :)

2023-06-28 17:35 UTC, fredcarle requested changes
Good improvements Islam. I have a few more things before I approve and then we should be good to go. I'm sorry if some of the comments are repetitive. I used some copy pasting to save me time :)

2023-06-28 17:35 UTC, fredcarle commented on api/http/handlerfuncs_index.go
> +	}
suggestion: You can replace this with 
```go
err := getJSON(req, &data)
if err != nil {
	handleErr(req.Context(), rw, err, http.StatusBadRequest)
	return
}
```

2023-06-28 17:35 UTC, fredcarle commented on api/http/handlerfuncs_index.go
> +	}
suggestion: Same as above.

2023-06-28 17:35 UTC, fredcarle commented on api/http/handlerfuncs_index.go
> +		)
suggestion: I think you can replace all this with 
```go
sendJSON(
	req.Context(),
	rw,
	simpleDataResponse("collections", indexesPerCol),
	http.StatusOK,
)
```

2023-06-28 17:35 UTC, fredcarle commented on cli/index_create.go
> +			}
todo: `e` should be changed to `err`.

2023-06-28 17:35 UTC, fredcarle commented on cli/index_drop.go
> +			}
todo: e should be changed to err.

2023-06-28 17:35 UTC, fredcarle commented on cli/index_list.go
> +			}
todo: e should be changed to err.

2023-06-28 17:35 UTC, fredcarle commented on cli/index_create_test.go
> +	err := addSchemaCmd.RunE(addSchemaCmd, []string{`type User { Name: String }`})
todo: We agreed to follow the convention of `Type` and `field` for our schemas. This should be changes to `type User { name: String }`.

2023-06-28 17:35 UTC, fredcarle commented on cli/index_list_test.go
> +	err := addSchemaCmd.RunE(addSchemaCmd, []string{`type User { Name: String }`})
todo: We agreed to follow the convention of `Type` and `field` for our schemas. This should be changes to `type User { name: String }`.

2023-06-28 17:35 UTC, fredcarle commented on tests/integration/cli/client_index_create_test.go
> +	createCollection(t, conf, `type User { Name: String }`)
todo: We agreed to follow the convention of `Type` and `field` for our schemas. This should be changes to `type User { name: String }`.

2023-06-28 17:35 UTC, fredcarle commented on tests/integration/cli/client_index_list_test.go
> +	createCollection(t, conf, `type User { Name: String }`)
todo: We agreed to follow the convention of `Type` and `field` for our schemas. This should be changes to `type User { name: String }`.

2023-06-28 17:35 UTC, fredcarle commented on tests/integration/cli/client_index_list_test.go
> +	createCollection(t, conf, `type Product { Name: String Price: Int }`)
todo: We agreed to follow the convention of `Type` and `field` for our schemas. This should be changes to `type Product { name: String, price: Int }`.

2023-06-29 11:27 UTC, shahzadlone commented on cli/index_create.go
> +  defradb client index create --collection Users --fields Name --name UsersByName`,
todo: Consistent use of `'` in examples.

One example has:
`--collection Users --fields Name`
Other has:
`--collection 'Users' --fields 'Name'`

2023-06-29 11:27 UTC, shahzadlone commented on cli/index_create.go
> +				}
todo: Seems like we want this `else` case tested.

Note: missing tests for the entire parent `else` block.

2023-06-29 11:27 UTC, shahzadlone commented on cli/index_create_test.go
> +		"--fields", "name", "--name", "users_name_index"})
nitpick: Slight pref for:

```suggestion
	indexCreateCmd.SetArgs(
		[]string{"--collection", "User","--fields", "name", "--name", "users_name_index"},
	)
```

OR

```suggestion
	indexCreateCmd.SetArgs([]string{
		"--collection", "User",
		"--fields", "name",
		"--name", "users_name_index",	
		},
	)
```

2023-06-29 11:27 UTC, shahzadlone commented on cli/index_drop.go
> +						logging.NewKV("Result", r.Data.Result))
todo: similar comment to above, seems to be missing tests for this case.

2023-06-29 11:27 UTC, shahzadlone commented on cli/index_list.go
> +						logging.NewKV("Collections", r.Data.Collections))
todo: Similar to other comments, missed test case?

2023-07-04 16:03 UTC, shahzadlone approved these changes
Some nitpicks above formatting, :P might be considered personal pref though. One minor todo.

Approving as all else LGTM =)

2023-07-04 16:03 UTC, shahzadlone commented on tests/integration/cli/client_index_drop_test.go
> +		"--collection", colName, "--fields", fieldName, "--name", indexName})
nitpick: similar format pref as other nitpick.

2023-07-04 16:03 UTC, shahzadlone commented on tests/integration/cli/client_index_drop_test.go
> +		"--collection", "User"})
nitpick: similar format pref as other nitpick.

2023-07-04 16:03 UTC, shahzadlone commented on tests/integration/cli/client_index_drop_test.go
> +		"--name", "users_name_index"})
nitpick: similar format pref as other nitpick.

2023-07-04 16:03 UTC, shahzadlone commented on tests/integration/cli/client_index_drop_test.go
> +		"--collection", "User", "--name", "users_name_index"})
nitpick: similar format pref as other nitpick.

2023-07-04 16:03 UTC, shahzadlone commented on tests/integration/cli/client_index_drop_test.go
> +		"--collection", "User", "--name", "users_name_index"})
nitpick: similar format pref as other nitpick.

2023-07-04 16:03 UTC, shahzadlone commented on tests/integration/cli/client_index_drop_test.go
> +		"--collection", "User", "--name", "users_name_index"})
nitpick: similar format pref as other nitpick.

2023-07-04 16:03 UTC, shahzadlone commented on tests/integration/cli/client_index_list_test.go
> +	//expectedResp := indexResp{Name: userColIndexOnNameFieldName, Fields: []indexFieldResp{{Name: "name"}}}
todo: Remove comment?

2023-07-04 16:06 UTC, fredcarle approved these changes
LGTM. Note that I do agree with Shahzad that changing the formatting of the command flags would help readability.

2023-07-04 16:36 UTC, merged