feat: Mutation typed input
sourcenetwork/defradb pull request #2167
Opened 2024-01-05 17:43 UTC by nasdf

## Relevant issue(s)

Resolves #2143 

## Description

This PR adds a typed input object for create and update mutation types.

Related SIP https://github.com/sourcenetwork/SIPs/discussions/10

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Make test

Specify the platform(s) on which this was tested:
- MacOS

2024-01-09 17:17 UTC, shahzadlone commented on request/graphql/schema/generate.go
> +		// Copy the loop variable before usage within the loop or it
Would appreciate a comment here mentioning `1.22` for regex search in the future, so can easily find some of these.

2024-01-09 17:19 UTC, shahzadlone requested changes
Why were the alias tests deleted? did we just drop support for aliases (i.e. a whole feature seems to have been dropped)?

2024-01-09 18:34 UTC, nasdf commented
> > As a side effect of this change the relationship alias has been replaced with the _id input field.
> 
> I don't understand what is meant by 'replaced' with the `type_id`, because before we had both the 'type' alias and 'type_id'.
> 
> Why were the alias tests deleted? did we just drop support for aliases (i.e. a whole feature seems to have been dropped)?
> 
> IIRC this was a feature that was requested by one of the partners, and was implemented in:
> 
> * [feat: Add alias to `groupBy` related object #1579](https://github.com/sourcenetwork/defradb/pull/1579)
> * [feat: Allow relation alias on create and update #1609](https://github.com/sourcenetwork/defradb/pull/1609)
> 
> More context: https://discord.com/channels/427944769851752448/1061831110956421150/1113950104517365900

We talked about this briefly in the standup last week. Since the mutation input fields are now typed it is not possible to support relation field aliases (unless we add gql union types).

2024-01-10 20:04 UTC, fredcarle requested changes
In order to not get this PR hung up by the reverting of the aliasing feature, lets keep the aliasing for now and lets try to reach consensus separately on what we want to do about the possibility of allowing embedded foreign objects.

Without the removal of aliasing, I think this PR can me approved and merged.

2024-01-10 21:13 UTC, fredcarle approved these changes

2024-01-10 21:14 UTC, fredcarle approved these changes
LGTM! Awesome work! I love that we now have this implemented.

If you don't mind just adding the 1.22 reference as mentionned by Shahzad before merging.

2024-01-10 21:21 UTC, shahzadlone requested changes
Sorry just reviewing, thanks for adding alias stuff back. I am mid review will appreciate if possible to wait for me to finish.

2024-01-10 21:23 UTC, shahzadlone commented on planner/create.go
> +			dataLabel: n.input,
todo: the name `dataLabel`doesn't make sense anymore. Please change to `inputLabel`

2024-01-10 22:46 UTC, shahzadlone reviewed
Cheers for this PR! I like it a lot! Left some var renaming todos and in addition have this todo:

In `planner/explain.go` file we have on line 56: 
```
dataLabel           = "data"
```

After renaming the variable please don't forget to change the value from`"data"` to `"input"`.

OR if you want to use `request.Input` in all those instances and just remove the `dataLabel`/`inputLabel` , I am okay with that too :)

2024-01-10 22:46 UTC, shahzadlone commented on client/request/consts.go
>  	Data        = "data"
todo: Please delete this `Data` variable now, it is now not used anywhere.

2024-01-10 22:46 UTC, shahzadlone commented on planner/update.go
> +	simpleExplainMap[dataLabel] = n.input
todo: Similar to other suggestions please change the variable name to be more relevant.

```suggestion
	simpleExplainMap[inputLabel] = n.input
```

2024-01-10 23:35 UTC, shahzadlone approved these changes
Cheers for doing all the todos!

2024-01-11 00:36 UTC, merged