refactor: Decouple net config
sourcenetwork/defradb pull request #2258
Opened 2024-01-26 22:47 UTC by nasdf

## Relevant issue(s)

#2257 

## Description

This is part of a larger refactor of the config package.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

make test

Specify the platform(s) on which this was tested:
- MacOS

2024-01-29 17:04 UTC, fredcarle requested changes
Nice work. Just one todo before approval :)

2024-01-29 17:23 UTC, nasdf commented on net/config.go
> +	ListenAddress     string
Since one of the addresses will always be localhost could we just add an `EnableLocalHost` option here?

2024-01-29 17:28 UTC, fredcarle commented on net/config.go
> +	ListenAddress     string
That's an option. I'm wondering if there may also be a situation where someone would want to listen on multiple ports 🤔

2024-01-29 19:16 UTC, nasdf commented on net/config.go
> +	ListenAddress     string
I've updated the config to support multiple addresses and set the default to localhost like we discussed.

2024-01-29 20:43 UTC, shahzadlone approved these changes
LGTM

2024-01-30 15:34 UTC, fredcarle approved these changes
LGTM

2024-01-30 15:34 UTC, fredcarle commented on config/configfile_yaml.gotmpl
> +    p2paddresses:
thought: `p2paddresses: {{ .Net.P2PAddresses }}` would also work.

2024-01-30 20:28 UTC, merged