Issue 3153 first commit
sourcenetwork/defradb pull request #3292
Opened 2024-12-04 21:35 UTC by ChrisBQu

## Relevant issue(s)

Resolves #3153

## Description

I have made it so that operationName and variables are supported by HTTP GET requests. I did this by modifying the `ExecRequest` function inside `http/handler_store.go` such that `operationName` and `variables` parameters are extracted if they are present.

I added two new tests to `http/handler_store_test.go` which test this functionality. See:

`TestExecRequest_WithValidQuery_HttpGet_WithOperationName_OmitsErrors`
and
`TestExecRequest_HttpGet_WithVariables_OmitsErrors`

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).

## How has this been tested?

The platform(s) on which this was tested:
- Windows

2024-12-04 22:05 UTC, fredcarle requested changes
Some initial comments :)

2024-12-04 22:05 UTC, fredcarle commented on http/handler_store_test.go
> +	}`
todo: Although the test does pass along the operation name in the query string, it doesn't test that it's actually passed to the GraphQL Request. To do so, the query might look like this
```go
query := `query UserQuery {
		User {
			name
		}
	}
        query UserQueryWithDocID {
		User {
                         _docID
			name
		}
	}`
```
And you can ensure that only the name field is returned to know that the operation name was correctly received. Even one operation might be enough to do so.

At the moment, this test will probably fail due to the operation not existing.

2024-12-04 22:05 UTC, fredcarle commented on playground/package-lock.json
todo: This shouldn't be part of this PR.

2024-12-04 22:08 UTC, fredcarle commented on http/handler_store_test.go
> +	}`
Seems like you fixed that already so I'll resolve the comment.

2024-12-05 15:42 UTC, ChrisBQu commented on playground/package-lock.json
I think I accidentally did that while trying to troubleshoot why defradb wasn't running on my machine anymore (restarting is actually all I needed to do.) In any case, I rolled it back. No harm, no foul. :)

2024-12-05 21:47 UTC, fredcarle approved these changes
LGTM! Thanks for taking care of this, Chris :)

2024-12-05 23:09 UTC, merged